config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/services'

  get 'welcome/partners'

  get 'welcome/aboutus'

  get 'welcome/contactus'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def services
  end

  def partners
  end

  def aboutus
  end

  def contactus
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Viva Africa"
      if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
      end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  
  <!--[if lt IE 7 ]> <html class="ie ie6 no-js" lang="en"> <![endif]-->
  <!--[if IE 7 ]>    <html class="ie ie7 no-js" lang="en"> <![endif]-->
  <!--[if IE 8 ]>    <html class="ie ie8 no-js" lang="en"> <![endif]-->
  <!--[if IE 9 ]>    <html class="ie ie9 no-js" lang="en"> <![endif]-->
  <!--[if gt IE 9]><!--><html class="no-js" lang="en"><!--<![endif]-->

<head>
  
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
  <title><%= full_title(yield(:title)) %></title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <meta name="description" content="The official website for Viva Africa Consulting LLP" />
  <meta name="keywords" content="viva, viva africa, llp, consulting, business, sageo, viva africa consulting" />
  <meta name="author" content="Ronnie Nyaga" />
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow:700" rel="stylesheet" />
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= favicon_link_tag 'vivalogo.ico' %>
  
  <%= javascript_include_tag "modernizr.custom.79639" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container demo-2">
    <%= render 'layouts/common/header' %>

    <%= yield %>

  </div>
  <%= render 'layouts/common/footer' %>
</body>
</html>

app/views/layouts/common/_footer.html.erb
<footer>

    <ul>
        <li>
            <p class="home">Home</p>
            <a class="logo" href="#">Viva Africa<i>&copy; 2015</i></a>
        </li>
        <li>
            <p class="services">Services</p>

            <ul>
                <li><a href="#">Service One</a></li>
                <li><a href="#">Service Two</a></li>
                <li><a href="#">Service Three</a></li>
                <li><a href="#">Service Four</a></li>
            </ul>
        </li>
        <li>
            <p class="reachus">Reach us</p>

            <ul>
                <li><a href="#">Email</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
                <li>020-xxxxxx</li>
            </ul>
        </li>
        <li>
            <p class="clients">Clients</p>

            <ul>
                <li><a href="#">Login Area</a></li>
                <li><a href="#">Support Center</a></li>
                <li><a href="#">FAQ</a></li>
            </ul>
        </li>
    </ul>

</footer>

app/views/layouts/common/_header.html.erb
<div class="container demo-2">
  <!-- Codrops top bar -->
  <div class="codrops-top clearfix">
    <a href="#">
      <strong>Viva Africa Consulting LLP </strong>
    </a>
    
    <!--The below section can uncommented when needed-->
    <!--
    <span class="right">
      <a href="#">Lorem Ipsum</a>
      <a href="#">
        <strong>Lorem Ipsum</strong>
      </a>
    </span>
    -->
    <div class="clr"></div>
  </div><!--/ Codrops top bar -->

  <header class="clearfix">

    <h1> <%= link_to image_tag("vivalogo.png"), root_url %><span>Lorem ipsum dolor</span></h1>    
    <nav class="codrops-demos">
      <%= link_to "Home", root_url %>
      <%= link_to "Serivces", welcome_services_path %>
      <%= link_to "Partners", welcome_partners_path %>
      <%= link_to "About Us", welcome_aboutus_path %>
      <%= link_to "Contact Us", welcome_contactus_path %>
    </nav>
  </header>

app/views/welcome/aboutus.html.erb
<h1>Welcome#aboutus</h1>
<p>Find me in app/views/welcome/aboutus.html.erb</p>

app/views/welcome/contactus.html.erb
<h1>Welcome#contactus</h1>
<p>Find me in app/views/welcome/contactus.html.erb</p>

app/views/welcome/index.html.erb
  <div id="slider" class="sl-slider-wrapper">
    <div class="sl-slider">
      <div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="-25" data-slice2-rotation="-25" data-slice1-scale="2" data-slice2-scale="2">
        <div class="sl-slide-inner">
          <div class="bg-img bg-img-1"></div>
          <h2>A bene placito.</h2>
          <blockquote><p>You have just dined, and however scrupulously the slaughterhouse is concealed in the graceful distance of miles, there is complicity.</p><cite>Ralph Waldo Emerson</cite></blockquote>
        </div>
      </div>
      
      <div class="sl-slide" data-orientation="vertical" data-slice1-rotation="10" data-slice2-rotation="-15" data-slice1-scale="1.5" data-slice2-scale="1.5">
        <div class="sl-slide-inner">
          <div class="bg-img bg-img-2"></div>
          <h2>Regula aurea.</h2>
          <blockquote><p>Until he extends the circle of his compassion to all living things, man will not himself find peace.</p><cite>Albert Schweitzer</cite></blockquote>
        </div>
      </div>
      
      <div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="3" data-slice2-rotation="3" data-slice1-scale="2" data-slice2-scale="1">
        <div class="sl-slide-inner">
          <div class="bg-img bg-img-3"></div>
          <h2>Dum spiro, spero.</h2>
          <blockquote><p>Thousands of people who say they 'love' animals sit down once or twice a day to enjoy the flesh of creatures who have been utterly deprived of everything that could make their lives worth living and who endured the awful suffering and the terror of the abattoirs.</p><cite>Dame Jane Morris Goodall</cite></blockquote>
        </div>
      </div>
      
      <div class="sl-slide" data-orientation="vertical" data-slice1-rotation="-5" data-slice2-rotation="25" data-slice1-scale="2" data-slice2-scale="1">
        <div class="sl-slide-inner">
          <div class="bg-img bg-img-4"></div>
          <h2>Donna nobis pacem.</h2>
          <blockquote><p>The human body has no more need for cows' milk than it does for dogs' milk, horses' milk, or giraffes' milk.</p><cite>Michael Klaper M.D.</cite></blockquote>
        </div>
      </div>
      
      <div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="-5" data-slice2-rotation="10" data-slice1-scale="2" data-slice2-scale="1">
        <div class="sl-slide-inner">
          <div class="bg-img bg-img-5"></div>
          <h2>Acta Non Verba.</h2>
          <blockquote><p>I think if you want to eat more meat you should kill it yourself and eat it raw so that you are not blinded by the hypocrisy of having it processed for you.</p><cite>Margi Clarke</cite></blockquote>
        </div>
      </div>
    </div><!-- /sl-slider -->

    <nav id="nav-dots" class="nav-dots">
      <span class="nav-dot-current"></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </nav>

  </div><!-- /slider-wrapper -->


<!--More to follow here-->


  <div class="content-wrapper" id="main">
    <header>
      <h1><span>Some</span> words about<span> us</span></h1>
    </header>
    <br>
      
      
      <div class="rightside">
        <%= image_tag("startup.png")%>
      </div>
      
      <div class="leftside">
        <h2>What we do?</h2>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget tellus vel ante blandit scelerisque. Cras vitae mauris eget turpis volutpat sagittis. Vestibulum sodales urna dui, a accumsan diam egestas mattis. Nam convallis semper libero eget molestie. Vivamus pharetra enim eget diam ultricies, vitae aliquam lorem egestas. Nunc vehicula sem ut rhoncus auctor. Ut sit amet molestie velit. Mauris sollicitudin rutrum tortor at ullamcorper. Praesent ut posuere lorem, eu elementum felis. Vestibulum leo neque, semper placerat est vitae, mattis suscipit eros. Sed luctus eros mauris, vel auctor mauris aliquam non.
      </p>
      
      
    <div class="margins">
      <h2 class="about round">About Us</h2>
        </div>
        <p>Some stuff goes here</p>
        
        <div class="margins">
          <h2 class="whyus round">Why Choose Us</h2>
        </div>
      </div>
      
      
    
      
    <ul class="ca-menu clearfix">
      <li>
        <a href="#">
          <span class="ca-icon">A</span>
          <div class="ca-content">
            <h2 class="ca-main">Exceptional Service</h2>
            <h3 class="ca-sub">Personalized to your needs</h3>
          </div>
        </a>                   
      </li>
      <li>
        <a href="#">
          <span class="ca-icon">I</span>
          <div class="ca-content">
            <h2 class="ca-main">Creative Storytelling</h2>
            <h3 class="ca-sub">Advanced use of technology</h3>
          </div>
        </a>                   
      </li>
      <li>
        <a href="#">
          <span class="ca-icon">C</span>
          <div class="ca-content">
            <h2 class="ca-main">Infographical Education</h2>
            <h3 class="ca-sub">Understanding visually</h3>
          </div>
        </a>                    
      </li>
      <li>
        <a href="#">
          <span class="ca-icon">S</span>
          <div class="ca-content">
            <h2 class="ca-main">Sophisticated Team</h2>
            <h3 class="ca-sub">Professionals in action</h3>
          </div>
        </a>  
      </li>
    </ul>
  </div>
  

<!--Javascript-->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>

<%= javascript_include_tag ("jsfooter_slider") %>

<script type="text/javascript">	
  $(function() {
    var Page = (function() {
      var $nav = $( '#nav-dots > span' ),
        slitslider = $( '#slider' ).slitslider( {
          onBeforeChange : function( slide, pos ) {
            $nav.removeClass( 'nav-dot-current' );
            $nav.eq( pos ).addClass( 'nav-dot-current' );
          }
        } ),
        init = function() {
          initEvents();        
        },
        initEvents = function() {
          $nav.each( function( i ) {        
            $( this ).on( 'click', function( event ) {                      
              var $dot = $( this );                    
              if( !slitslider.isActive() ) {
                $nav.removeClass( 'nav-dot-current' );
                $dot.addClass( 'nav-dot-current' );
              }
              slitslider.jump( i + 1 );
              return false;
            } );              
          } );
        };
      return { init : init };
    })();

Page.init();

  /**
   * Notes: 
   * 
   * example how to add items:
   */

  /*
  
  var $items  = $('<div class="sl-slide sl-slide-color-2" data-orientation="horizontal" data-slice1-rotation="-5" data-slice2-rotation="10" data-slice1-scale="2" data-slice2-scale="1"><div class="sl-slide-inner bg-1"><div class="sl-deco" data-icon="t"></div><h2>some text</h2><blockquote><p>bla bla</p><cite>Margi Clarke</cite></blockquote></div></div>');
  
  // call the plugin's add method
  ss.add($items);

  */

  });
</script>

app/views/welcome/partners.html.erb
<h1>Welcome#partners</h1>
<p>Find me in app/views/welcome/partners.html.erb</p>

app/views/welcome/services.html.erb
<h1>Welcome#services</h1>
<p>Find me in app/views/welcome/services.html.erb</p>